#baseURL = 'https://nullenvk.pl/'
baseURL = 'https://nullenvk.pages.lain.la/personal-site/'
languageCode = 'en-us'
title = "Nullenvk's blog"
theme = 'no-style-please'

[params]
    [params.theme_config]
        appearance = "dark"
        back_home_text = ".."
        date_format = "2006-01-02"
