baseURL = 'https://nullenvk.pl/'
languageCode = 'en-us'
title = "Nullenvk's blog"
author = "Nullenvk"
theme = 'my-theme'

[params]
    author = "nullenvk"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10
